update

diff --git a/.github/workflows/call_script.yaml b/.github/workflows/call_script.yaml
--- a/.github/workflows/call_script.yaml
+++ b/.github/workflows/call_script.yaml
@@ -80,7 +80,7 @@ jobs:
       - name: Debug output file
         run: |
           echo "=== Contents of global_vars.hcl ==="
-          cat ./script/global_vars.hcl || echo "File not found"
+          cat ${{ env.TARGET_DIR }}global_vars.hcl || echo "File not found"
 
       - name: Upload global_vars.hcl as artifact
         uses: actions/upload-artifact@v4
